name: Distribute Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Distribute
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Set up poetry
        uses: abatilo/actions-poetry@v2.2.0
        with:
          poetry-version: 1.3.2
      - name: Publish
        run: |
          poetry config http-basic.pypi ${{ secrets.PYPI_USERNAME }} ${{ secrets.PYPI_PASSWORD }}
          poetry publish --build
