name: Release

on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: python
          package-name: czds
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          include-v-in-tag: false
