name: Release

on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: python
          package-name: czds
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          include-v-in-tag: false
      # The logic below handles the PyPi distribution:
      - uses: actions/checkout@v3
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
        if: ${{ steps.release.outputs.release_created }}
      - name: Set up poetry
        uses: abatilo/actions-poetry@v2.2.0
        with:
          poetry-version: 1.3.2
        if: ${{ steps.release.outputs.release_created }}
      - name: Publish
        run: |
          poetry config http-basic.pypi ${{ secrets.PYPI_USERNAME }} ${{ secrets.PYPI_PASSWORD }}
          poetry publish --build
        if: ${{ steps.release.outputs.release_created }}
